language: php

matrix:
    include:
        - php: 7.1

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpenv config-rm xdebug.ini || return 0
    # Check the style rules are applied
    - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
    # Run PHPUnit
    - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN="88a73a48685982ddd8ed5ba5e4b5fc098f9fa3419cb88aebb043ea0d32dad428" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: 88a73a48685982ddd8ed5ba5e4b5fc098f9fa3419cb88aebb043ea0d32dad428

after_success:
    - php vendor/bin/coveralls -v
